### ISSUE TITLE
Representable instances are dangerous

### ISSUE THREAD

**Issue by gittywithexcitement** [tonyday567/tower#18]
The Reprsentable instances of the various additive, multiplicative, etc. typeclasses are dangerous. It lead to silent bug(s) in my program when I was multiplying Complex numbers.  See https://github.com/tonyday567/tower/pull/17

If you think they are too valuable to tear out, then please at least put a large warning note.  I could imagine types other than Complex that would also not want the default instances defined for any Representable type. For example, a Polynomial type would want multiplication to use a convolution, not element-wise multiply.

**Comment by tonyday567** [comment]
Yep, I agree.  I'll take em out.

**Comment by tonyday567** [comment]
I just realised this is in tower.  I moved development to a new repository - tonyday567/numhask  - sorry I forgot to put up notice.

**Comment by gittywithexcitement** [comment]
Ok, thanks. Closing.
